services:
  mongo:
    image : mongo:6.0
    container_name : MONGO_DB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:7.0.5-alpine
    container_name: REDIS_DB
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local