spring.data.mongodb.host=${MONGO_HOST:localhost}
spring.data.mongodb.port=${MONGO_PORT:27017}
spring.data.mongodb.database=${MONGO_DATABASE:card-game}
spring.data.mongodb.username=${MONGO_USERNAME:root}
spring.data.mongodb.password=${MONGO_PASSWORD:example}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}